"""builder.py - Phase 8: `set_company_up(mode="text"|"gui")`.

Two genuinely different-sized builds under one name, as the roadmap frames it.

**Text/schema mode** (this file, and the smaller half): a company builder
shaped so an *AI* can call it. The whole design constraint is that the calling
model must be able to see what its options are and fill them in correctly, so:

- The schema is **generated by `core.ToolRegistry`** from the type hints and
  docstring of `set_up_company`, not hand-written in a parallel format. That
  was the explicit instruction, and it has a real payoff: the tool an agent
  calls and the schema it reads are the same function, so they cannot drift.
- Because `ToolRegistry`'s auto-schema maps flat scalars, `set_up_company`
  takes **flat scalar parameters** - names, an org-template name, a size, a
  budget - plus one optional `employees_json` escape hatch for org shapes no
  template covers. A nested-object schema would have needed a second schema
  generator, which is the thing this phase was told not to build.
- `company_options()` returns the valid names for every preset kind straight
  from Phase 5's `PresetBundle.names()`. This is why text mode depends on
  Phase 5 existing: a schema that says `template: str` is useless to a model,
  while one whose description carries the actual template names is usable.

**GUI mode**: a real interactive node-graph editor, which is a small web app
rather than a Python function. It lives in `gui.py`; `set_company_up(
mode="gui")` dispatches to it. See that module for its own scope notes.

What text mode deliberately does not do: it builds and returns a `Company`,
it does not run anything. Building is cheap and reversible; running spends
money. An AI that can build a company in one tool call and start it in the
same call is one hallucinated argument away from a bill, so the caller has to
take the second step themselves.
"""

import json
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence

from .company import Company, EscalationDecision, EscalationEvent
from .core import ToolRegistry
from .presets import ORG_TEMPLATES, PALETTES, PERSONALITIES, SKILLS, TASK_SIZES, default_bundle
from .router import RoleRank

# A rank -> model_map entry used when the caller supplies no model_map at all.
# Everything routes to Ollama locally, which is the only provider that needs no
# API key - so a company built by an AI with no configuration cannot
# accidentally start spending money. Override with model_map= for real use.
DEFAULT_MODEL_MAP: Dict[str, Dict[str, Any]] = {
    rank: {"provider": "ollama", "model": "llama3.1:8b", "mode": "auto"}
    for rank in RoleRank.ORDER
}


def default_on_escalation(event: EscalationEvent) -> EscalationDecision:
    """The escalation callback used when the caller supplies none.

    Declines. That is the deliberate choice, matching the 0-means-always-ask
    defaults Phases 0-3 set for both emergency reserves: a company built
    programmatically (possibly by another AI) has no human attached to it, and
    "no human available" must mean "stop", never "approve yourself".
    """
    return EscalationDecision(
        approve=False,
        note="No on_escalation handler was configured for this company, so the request was declined.",
    )


# ---------------------------------------------------------------------------
# The spec
# ---------------------------------------------------------------------------


@dataclass
class EmployeeSpec:
    """One employee in a hand-written company spec."""

    name: str
    rank: str = RoleRank.SENIOR
    reports_to: Optional[str] = None
    skills: Sequence[str] = ()
    personality: Optional[str] = None
    effort: Optional[str] = None
    specialty: Optional[str] = None
    importance: float = 0.5
    provider: Optional[str] = None
    model: Optional[str] = None
    mode: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EmployeeSpec":
        if not isinstance(data, dict):
            raise ValueError(f"each employee must be an object, got {type(data).__name__}")
        if not data.get("name"):
            raise ValueError("each employee needs a 'name'")
        known = {f for f in cls.__dataclass_fields__}  # noqa: SLF001 - dataclass API
        unknown = set(data) - known
        if unknown:
            raise ValueError(f"employee {data['name']!r} has unknown field(s): {', '.join(sorted(unknown))}")
        return cls(**data)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name, "rank": self.rank, "reports_to": self.reports_to,
            "skills": list(self.skills), "personality": self.personality,
            "effort": self.effort, "specialty": self.specialty, "importance": self.importance,
            "provider": self.provider, "model": self.model, "mode": self.mode,
        }


@dataclass
class CompanySpec:
    """Everything needed to build a Company, as plain data.

    This is the format `gui.py` saves and loads too, so the GUI and the text
    tool produce the same artifact and either can consume the other's output.
    """

    name: str = "New Company"
    template: Optional[str] = None
    size: str = "small"
    employees: List[EmployeeSpec] = field(default_factory=list)
    palette: str = "dataviz"
    total_token_budget: Optional[int] = None
    emergency_budget_tokens: int = 0
    emergency_iteration_reserve: int = 0
    review_mode: str = "critique"
    max_review_rounds: int = 1
    notes: str = ""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CompanySpec":
        data = dict(data or {})
        employees = [EmployeeSpec.from_dict(e) for e in data.pop("employees", []) or []]
        known = {f for f in cls.__dataclass_fields__}  # noqa: SLF001
        unknown = set(data) - known
        if unknown:
            raise ValueError(f"unknown company field(s): {', '.join(sorted(unknown))}")
        return cls(employees=employees, **data)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name, "template": self.template, "size": self.size,
            "employees": [e.to_dict() for e in self.employees], "palette": self.palette,
            "total_token_budget": self.total_token_budget,
            "emergency_budget_tokens": self.emergency_budget_tokens,
            "emergency_iteration_reserve": self.emergency_iteration_reserve,
            "review_mode": self.review_mode, "max_review_rounds": self.max_review_rounds,
            "notes": self.notes,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, text: str) -> "CompanySpec":
        return cls.from_dict(json.loads(text))

    def validate(self, bundle: Optional[Any] = None) -> List[str]:
        """Returns a list of human-readable problems - empty means valid.

        Returns rather than raises because the caller here is often a model
        filling in a schema, and "here are the four things wrong with what you
        sent" is a far more useful reply than a traceback on the first one.
        """
        bundle = bundle or default_bundle()
        problems: List[str] = []

        if not self.name:
            problems.append("company needs a name")
        if self.size not in TASK_SIZES:
            problems.append(f"size {self.size!r} is not one of: {', '.join(TASK_SIZES)}")
        if self.template and self.template not in bundle.org_templates:
            problems.append(
                f"unknown template {self.template!r}. Available: {', '.join(bundle.org_templates.names())}"
            )
        if self.palette and self.palette not in bundle.palettes:
            problems.append(
                f"unknown palette {self.palette!r}. Available: {', '.join(bundle.palettes.names())}"
            )
        if self.review_mode not in ("critique", "append", "off"):
            problems.append(f"review_mode {self.review_mode!r} is not one of: critique, append, off")
        if not self.template and not self.employees:
            problems.append("give either a template or at least one employee")

        names = [e.name for e in self.employees]
        for duplicate in {n for n in names if names.count(n) > 1}:
            problems.append(f"duplicate employee name {duplicate!r} - names must be unique")

        # A hand-written employee may report to someone the *template* creates,
        # since a spec is allowed to extend a template rather than replace it.
        # Those names don't exist until build time, so derive them here.
        known_names = set(names)
        if self.template and self.template in bundle.org_templates and self.size in TASK_SIZES:
            template = bundle.org_templates.get(self.template)
            for role in template.roles_for(self.size):
                count = role.count_for(self.size)
                for index in range(count):
                    suffix = f" {index + 1}" if count > 1 else ""
                    known_names.add(f"{role.display_title()}{suffix}")

        for employee in self.employees:
            if employee.rank not in RoleRank.ORDER:
                problems.append(
                    f"{employee.name}: unknown rank {employee.rank!r}. "
                    f"Available: {', '.join(RoleRank.ORDER)}"
                )
            if employee.reports_to and employee.reports_to not in known_names:
                problems.append(
                    f"{employee.name}: reports_to {employee.reports_to!r}, who is not in this company"
                )
            for skill in employee.skills:
                if skill not in bundle.skills:
                    problems.append(
                        f"{employee.name}: unknown skill {skill!r}. "
                        f"Available: {', '.join(bundle.skills.names())}"
                    )
            if employee.personality and employee.personality not in bundle.personalities:
                problems.append(
                    f"{employee.name}: unknown personality {employee.personality!r}. "
                    f"Available: {', '.join(bundle.personalities.names())}"
                )

        # Reporting cycles - the same check org templates get, since a
        # hand-written spec can describe one just as easily.
        by_name = {e.name: e for e in self.employees}
        for employee in self.employees:
            seen = {employee.name}
            cursor = employee.reports_to
            while cursor and cursor in by_name:
                if cursor in seen:
                    problems.append(f"reporting cycle involving {cursor!r}")
                    break
                seen.add(cursor)
                cursor = by_name[cursor].reports_to

        return problems


# ---------------------------------------------------------------------------
# Building
# ---------------------------------------------------------------------------


@dataclass
class BuildResult:
    """The structured "what got built" an AI caller needs back.

    `company` is the live object; everything else is JSON-serializable so the
    whole thing can be handed straight back through a tool result.
    """

    company: Optional[Company] = None
    spec: Optional[CompanySpec] = None
    problems: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.company is not None and not self.problems

    def to_dict(self) -> Dict[str, Any]:
        out: Dict[str, Any] = {
            "ok": self.ok,
            "problems": list(self.problems),
            "warnings": list(self.warnings),
        }
        if self.spec is not None:
            out["spec"] = self.spec.to_dict()
        if self.company is not None:
            out["company"] = self.company.name
            out["employees"] = [
                {
                    "name": e.name, "rank": e.rank,
                    "reports_to": e.reports_to.name if e.reports_to else None,
                    "skills": [getattr(s, "name", s) for s in e.skills],
                    "personality": getattr(e.personality, "name", e.personality),
                    "effort": e.effort, "specialty": e.specialty,
                    "provider": e.agent.provider, "model": e.agent.model,
                }
                for e in self.company.employees.values()
            ]
            out["teams"] = [
                {"name": t.name, "lead": t.lead.name,
                 "reviewer": t.reviewer.name if t.reviewer else None,
                 "members": [m.name for m in t.members],
                 "review_mode": t.review_mode}
                for t in self.company.teams
            ]
            out["org_chart"] = self.company.render_org_chart(fmt="ascii")
        return out


def build_company(
    spec: CompanySpec,
    model_map: Optional[Dict[str, Dict[str, Any]]] = None,
    on_escalation: Optional[Callable[[EscalationEvent], EscalationDecision]] = None,
    model_policy: Optional[Any] = None,
    presets: Optional[Any] = None,
    log_compaction: Optional[Any] = None,
) -> BuildResult:
    """Turn a CompanySpec into a live Company.

    Validation runs first and a failing spec returns a BuildResult with
    `problems` and no company - nothing is half-built. Runtime concerns
    (model_map, on_escalation, model_policy, presets, log_compaction) are
    arguments rather than spec fields on purpose: they are callables and
    policy objects, they don't serialize, and putting them in the spec would
    mean an AI-authored JSON blob could name a provider and an API key. The
    spec describes the *org*; the caller supplies the *runtime*.
    """
    presets = presets or default_bundle()
    problems = spec.validate(presets)
    if problems:
        return BuildResult(spec=spec, problems=problems)

    warnings: List[str] = []
    if model_map is None:
        model_map = DEFAULT_MODEL_MAP
        warnings.append(
            "no model_map given - every rank defaults to a local Ollama model, so this "
            "company cannot spend money until you configure one"
        )
    if on_escalation is None:
        on_escalation = default_on_escalation
        warnings.append(
            "no on_escalation handler given - escalations will be declined automatically"
        )
    if spec.total_token_budget is None:
        warnings.append(
            "no total_token_budget set - this company has no spend ceiling (see Phase 3)"
        )

    company = Company(
        name=spec.name,
        model_map=model_map,
        on_escalation=on_escalation,
        total_token_budget=spec.total_token_budget,
        emergency_budget_tokens=spec.emergency_budget_tokens,
        emergency_iteration_reserve=spec.emergency_iteration_reserve,
        model_policy=model_policy,
        presets=presets,
        log_compaction=log_compaction,
    )

    if spec.template:
        company.build_from_template(
            spec.template, size=spec.size,
            review_mode=spec.review_mode, max_review_rounds=spec.max_review_rounds,
        )

    # Hand-written employees are hired after any template, parents first, so
    # a spec can extend a template as well as replace it.
    pending = list(spec.employees)
    guard = len(pending) + 1
    while pending and guard:
        guard -= 1
        for employee in list(pending):
            manager = None
            if employee.reports_to:
                manager = company.employees.get(employee.reports_to)
                if manager is None:
                    continue  # manager not hired yet - try again next pass
            company.hire(
                name=employee.name, rank=employee.rank, reports_to=manager,
                skills=employee.skills, personality=employee.personality,
                effort=employee.effort, specialty=employee.specialty,
                importance=employee.importance, provider=employee.provider,
                model=employee.model, mode=employee.mode,
            )
            pending.remove(employee)
    if pending:  # validate() rules this out; belt and braces
        return BuildResult(
            spec=spec,
            problems=[f"could not resolve reporting lines for: {', '.join(e.name for e in pending)}"],
        )

    company._log("company_built", employee=None, template=spec.template, size=spec.size,
                 headcount=len(company.employees))
    return BuildResult(company=company, spec=spec, warnings=warnings)


# ---------------------------------------------------------------------------
# The AI-facing tool
# ---------------------------------------------------------------------------


def company_options(bundle: Optional[Any] = None) -> Dict[str, List[str]]:
    """The valid names for everything `set_up_company` accepts.

    Straight from Phase 5's registries - this is the dependency that made text
    mode wait for Phase 5. Give this to a model alongside the schema; a schema
    saying `template: str` tells it nothing, while the actual list of template
    names makes the tool usable in one shot.
    """
    bundle = bundle or default_bundle()
    options = bundle.names()
    options["ranks"] = list(RoleRank.ORDER)
    options["sizes"] = list(TASK_SIZES)
    options["review_modes"] = ["critique", "append", "off"]
    return options


def set_up_company(
    name: str,
    template: str = "",
    size: str = "small",
    palette: str = "dataviz",
    total_token_budget: int = 0,
    review_mode: str = "critique",
    max_review_rounds: int = 1,
    employees_json: str = "",
    notes: str = "",
) -> str:
    """Create a multi-agent company and report what was built.

    Builds the org only - it does not run any task, so calling this costs
    nothing. Call company_options() first to see the valid names for template,
    skills, personalities and palettes.

    name: what to call the company.
    template: a ready-made org shape by name, e.g. 'small-coding-team'. Leave
        empty to describe the employees yourself in employees_json.
    size: 'small', 'medium' or 'large' - how far to scale the template's
        worker roles. Ignored when no template is given.
    palette: the org-chart colour scheme by name, e.g. 'dataviz'.
    total_token_budget: a hard ceiling on total tokens this company may spend.
        0 means no ceiling, which is the riskier choice.
    review_mode: 'critique' (reviewer can send work back), 'append' (reviewer
        gives a second opinion) or 'off' (no review).
    max_review_rounds: how many times a reviewer may send work back.
    employees_json: a JSON array of employees, for org shapes no template
        covers. Each entry looks like {"name": "Ada", "rank": "SENIOR",
        "reports_to": "Grace", "skills": ["python"], "personality": "concise",
        "effort": "balanced", "importance": 0.5}. Can be combined with a
        template to extend it.
    notes: free text stored with the spec, for whoever reads it later.

    Returns a JSON report: whether it worked, the employees and teams created,
    an ASCII org chart, and any problems or warnings.
    """
    result = set_company_up(
        mode="text", name=name, template=template, size=size, palette=palette,
        total_token_budget=total_token_budget, review_mode=review_mode,
        max_review_rounds=max_review_rounds, employees_json=employees_json, notes=notes,
    )
    # to_dict() already carries only the company's *name*, never the live
    # object - a tool result has to survive json.dumps.
    return json.dumps(result.to_dict(), indent=2, default=str)


def company_setup_schema(bundle: Optional[Any] = None) -> Dict[str, Any]:
    """The tool schema for `set_up_company`, generated by `ToolRegistry`.

    Deliberately generated rather than written: `ToolRegistry.register()`
    already derives a schema from type hints plus the docstring, so the tool
    an agent calls and the schema it reads come from the same function and
    cannot drift apart. This adds one thing on top - the live preset names
    from Phase 5's registries appended to the relevant parameter descriptions,
    which is the difference between a schema a model can guess at and one it
    can fill in correctly.
    """
    registry = ToolRegistry()
    registry.register(set_up_company)
    schema = json.loads(json.dumps(registry.schemas["set_up_company"]))  # deep copy

    options = company_options(bundle)
    enrichment = {
        "template": options["org_templates"],
        "size": options["sizes"],
        "palette": options["palettes"],
        "review_mode": options["review_modes"],
    }
    properties = schema.get("parameters", {}).get("properties", {})
    for param, values in enrichment.items():
        if param in properties:
            properties[param]["enum"] = list(values)
            properties[param]["description"] = (
                f"{properties[param].get('description', '')} One of: {', '.join(values)}."
            ).strip()
    if "employees_json" in properties:
        properties["employees_json"]["description"] += (
            f" Valid ranks: {', '.join(options['ranks'])}."
            f" Valid skills: {', '.join(options['skills'])}."
            f" Valid personalities: {', '.join(options['personalities'])}."
        )
    return schema


def register_company_builder(agent: Any) -> Any:
    """Give an Agent the ability to build companies.

    One line for the common case: `register_company_builder(my_agent)` and the
    agent can now call set_up_company through the ordinary tool-calling loop,
    with the enriched schema.
    """
    agent.add_tool(set_up_company, schema=company_setup_schema())
    return agent


# ---------------------------------------------------------------------------
# The entry point named in the roadmap
# ---------------------------------------------------------------------------


def set_company_up(mode: str = "text", **kwargs: Any) -> Any:
    """Build a company. Two genuinely different modes under one name.

    mode="text" - build from arguments (or a spec) and return a BuildResult.
        This is the AI-callable path; `set_up_company` is the same thing
        wrapped as a tool returning JSON.
    mode="gui" - open the interactive node-graph editor (see gui.py) and
        return whatever the user built there.

    Text-mode arguments are the fields of CompanySpec, plus the runtime
    arguments of build_company (model_map, on_escalation, model_policy,
    presets, log_compaction). Pass `spec=` to supply a CompanySpec or dict
    directly instead of field by field.
    """
    mode = (mode or "text").strip().lower()
    if mode == "gui":
        from .gui import launch_gui

        return launch_gui(**kwargs)
    if mode != "text":
        raise ValueError(f"unknown mode {mode!r} - use 'text' or 'gui'")

    runtime_keys = ("model_map", "on_escalation", "model_policy", "presets", "log_compaction")
    runtime = {k: kwargs.pop(k) for k in runtime_keys if k in kwargs}

    spec_arg = kwargs.pop("spec", None)
    if spec_arg is not None:
        spec = spec_arg if isinstance(spec_arg, CompanySpec) else CompanySpec.from_dict(spec_arg)
    else:
        employees_json = kwargs.pop("employees_json", "") or ""
        employees: List[Dict[str, Any]] = []
        if str(employees_json).strip():
            try:
                parsed = json.loads(employees_json)
            except json.JSONDecodeError as e:
                return BuildResult(problems=[f"employees_json is not valid JSON: {e}"])
            if not isinstance(parsed, list):
                return BuildResult(problems=["employees_json must be a JSON array of employee objects"])
            employees = parsed

        # An empty-string template means "none", and a 0 budget means "no
        # ceiling" - both because ToolRegistry's flat scalar schema has no way
        # to express null, so the sentinel has to live here.
        kwargs["template"] = kwargs.get("template") or None
        budget = kwargs.pop("total_token_budget", None)
        kwargs["total_token_budget"] = budget if budget else None
        try:
            spec = CompanySpec.from_dict({**kwargs, "employees": employees})
        except (ValueError, TypeError) as e:
            return BuildResult(problems=[str(e)])

    return build_company(spec, **runtime)


__all__ = [
    "CompanySpec", "EmployeeSpec", "BuildResult",
    "build_company", "set_company_up", "set_up_company",
    "company_setup_schema", "company_options", "register_company_builder",
    "default_on_escalation", "DEFAULT_MODEL_MAP",
]
